[package]
name = "universal-hdwallet"
version = "0.1.0"
edition = "2021"

[dependencies]
bip39 = "2.0.0"
ethereum-types = "0.14.1"
web3 = "0.19.0"
secp256k1 = { version = "0.27.0", features = ["rand"] }
hex = "0.4.3"
tiny-keccak = { version = "2.0.2", features = ["keccak"] }
anyhow = "1.0"
tokio = { version = "1.0", features = ["full"] }
thiserror = "1.0"
rand = "0.8"
