[package]
name = "digital-signature-system"
version = "0.1.0"
edition = "2021"

[dependencies]
# Cryptography
ed25519-dalek = "1.0"
rsa = "0.9"
rand = "0.8"
aes-gcm = "0.10"
base64 = "0.21"

# GUI
eframe = "0.22"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true