[package]
name = "cross-chain-protocol"
version = "0.1.0"
edition = "2021"
authors = "PromiseGameFi"
description = "A universal blockchain account system enabling seamless cross-chain interactions"
license = "MIT"
readme = "README.md"
repository = "https://github.com/PromiseGameFi/Blockchain-L1-for-Gaming/tree/main/ChainAbstraction"
keywords = ["blockchain", "cross-chain", "web3", "cryptocurrency"]
categories = ["cryptography", "blockchain"]

[dependencies]
# Async runtime
tokio = { version = "1.36", features = ["full"] }
async-trait = "0.1.77"

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Error handling
thiserror = "1.0"
anyhow = "1.0"



# Utilities
futures = "0.3"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
dotenv = "0.15"
url = "2.5"

# Storage
sqlx = { version = "0.7", features = ["runtime-tokio", "tls-rustls", "postgres"] }
redis = { version = "0.24", features = ["tokio-comp", "connection-manager"] }
